---
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
      
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes
    - name: Add Node.js subdomain to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 node.localhost"
        state: present
      become: yes

    - name: Add Python subdomain to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 python.localhost"
        state: present
      become: yes
    - name: Configure Nginx for Node.js and Python reverse proxy
      template:
        src: default_file.conf.j2
        dest: /etc/nginx/sites-available/default
      become: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: yes

