---
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Node.js dependencies
      npm:
        path: /home/vagrant/nodeProject/
      become: no

    - name: Install nodemon
      shell: "npm install nodemon"
      args:
        chdir: /home/vagrant/nodeProject/

    - name: Run Node.js project
      shell: "nohup npm start &"
      args:
        chdir: /home/vagrant/nodeProject/
      async: 60
      poll: 0
      become: no
